#!/usr/bin/env bash
set -Eeuo pipefail

red=$'\033[0;31m'; green=$'\033[0;32m'; yellow=$'\033[0;33m'; blue=$'\033[0;34m'; reset=$'\033[0m'
info(){ printf '%s[INFO]%s %s\n' "$blue" "$reset" "$*"; }
ok(){ printf '%s[OK]%s %s\n' "$green" "$reset" "$*"; }
warn(){ printf '%s[WARN]%s %s\n' "$yellow" "$reset" "$*"; }
fail(){ printf '%s[ERROR]%s %s\n' "$red" "$reset" "$*" >&2; exit 1; }
trap 'fail "Failed at line $LINENO: $BASH_COMMAND"' ERR

OPENXPKI_CONFIG_DIR="${OPENXPKI_CONFIG_DIR:-/etc/openxpki}"
OPENXPKI_REALM="${OPENXPKI_REALM:-}"
OPENXPKI_REALM_LABEL="${OPENXPKI_REALM_LABEL:-}"
OPENXPKI_BASEURL="${OPENXPKI_BASEURL:-}"
OPENXPKI_CA_SUBJECT="${OPENXPKI_CA_SUBJECT:-}"
OPENXPKI_CA_DAYS="${OPENXPKI_CA_DAYS:-3650}"
OPENXPKI_DEFAULT_SECRET="${OPENXPKI_DEFAULT_SECRET:-}"
OPENXPKI_RATOKEN_SECRET="${OPENXPKI_RATOKEN_SECRET:-}"
OPENXPKI_SVAULT_KEY="${OPENXPKI_SVAULT_KEY:-}"
OPENXPKI_CREATE_ISSUER="${OPENXPKI_CREATE_ISSUER:-ask}"
OPENXPKI_ISSUER_CERT="${OPENXPKI_ISSUER_CERT:-}"
OPENXPKI_ISSUER_KEY="${OPENXPKI_ISSUER_KEY:-}"

require_root(){ [[ $EUID -eq 0 ]] || fail "Run as root inside the OpenXPKI container."; }
need(){ command -v "$1" >/dev/null 2>&1 || fail "Missing command: $1"; }
yaml_sq(){ printf "'"; printf '%s' "$1" | sed "s/'/''/g"; printf "'"; }

ask(){
  local prompt="$1" default="$2" value
  read -r -p "${prompt} [${default}]: " value
  printf '%s' "${value:-$default}"
}

ask_yes_no(){
  local prompt="$1" default="${2:-n}" value suffix
  if [[ "$default" == "y" ]]; then suffix="Y/n"; else suffix="y/N"; fi
  read -r -p "${prompt} [${suffix}]: " value
  value="${value:-$default}"
  [[ "$value" =~ ^[Yy]$ ]]
}

prompt_secret_or_generate(){
  local var_name="$1" prompt="$2" length="${3:-32}" mode="${4:-base64}" first second generated
  if [[ -n "${!var_name:-}" ]]; then return 0; fi
  read -r -s -p "${prompt} [leave blank to generate]: " first
  echo
  if [[ -z "$first" ]]; then
    if [[ "$mode" == "hex" ]]; then
      generated="$(openssl rand -hex $((length / 2)))"
    else
      generated="$(openssl rand -base64 48 | tr -d '\n' | tr -d '=+/ ' | cut -c1-"$length")"
    fi
    printf -v "$var_name" '%s' "$generated"
    warn "Generated ${var_name}; it will be recorded in /root/OPENXPKI-PRODUCTION-SECRETS.txt. Store it securely."
    return 0
  fi
  read -r -s -p "Confirm ${prompt}: " second
  echo
  [[ "$first" == "$second" ]] || fail "Values did not match."
  printf -v "$var_name" '%s' "$first"
}

safe_realm(){
  [[ "$OPENXPKI_REALM" =~ ^[a-zA-Z0-9_-]+$ ]] || fail "Realm must use only letters, numbers, underscore, or hyphen."
}

collect_inputs(){
  OPENXPKI_REALM="${OPENXPKI_REALM:-$(ask "PKI realm name" "productionca")}"; safe_realm
  OPENXPKI_REALM_LABEL="${OPENXPKI_REALM_LABEL:-$(ask "Realm label" "Production CA")}" 
  OPENXPKI_BASEURL="${OPENXPKI_BASEURL:-$(ask "Realm base URL" "https://pki.example.com/webui/${OPENXPKI_REALM}/")}" 
  OPENXPKI_CA_SUBJECT="${OPENXPKI_CA_SUBJECT:-$(ask "Issuer CA subject" "/CN=${OPENXPKI_REALM_LABEL}/O=Example Org/C=US")}" 
  OPENXPKI_CA_DAYS="${OPENXPKI_CA_DAYS:-$(ask "Issuer CA validity days" "3650")}" 
  prompt_secret_or_generate OPENXPKI_DEFAULT_SECRET "OpenXPKI default token secret" 32 base64
  prompt_secret_or_generate OPENXPKI_RATOKEN_SECRET "OpenXPKI RA token secret" 32 base64
  prompt_secret_or_generate OPENXPKI_SVAULT_KEY "OpenXPKI symmetric datavault key (64 hex chars)" 64 hex
  [[ "$OPENXPKI_SVAULT_KEY" =~ ^[0-9a-fA-F]{64}$ ]] || fail "SVAULT key must be 64 hex characters."
}

write_system_crypto(){
  info "Writing system crypto secrets"
  cp -a "$OPENXPKI_CONFIG_DIR/config.d/system/crypto.yaml" "/root/system.crypto.yaml.backup.$(date +%Y%m%d%H%M%S)" 2>/dev/null || true
  cat >"$OPENXPKI_CONFIG_DIR/config.d/system/crypto.yaml" <<EOF
# Generated by OpenXPKI helper production setup.
token:
    default:
        backend: OpenXPKI::Crypto::Backend::OpenSSL
        api:     OpenXPKI::Crypto::Backend::API
        engine:  OpenSSL
        key_store: OPENXPKI
        shell: /usr/bin/openssl
        wrapper: ''
        randfile: /var/openxpki/rand

secret:
    default:
        label: Global secret group
        export: 0
        method: literal
        value: $(yaml_sq "$OPENXPKI_DEFAULT_SECRET")

    ratoken:
        label: Secret group for RA Token
        export: 1
        method: literal
        value: $(yaml_sq "$OPENXPKI_RATOKEN_SECRET")

    svault:
        label: Secret group for datavault encryption key
        method: literal
        value: $(yaml_sq "$OPENXPKI_SVAULT_KEY")
EOF
  chmod 0640 "$OPENXPKI_CONFIG_DIR/config.d/system/crypto.yaml"
}

write_realm_config(){
  info "Writing realm configuration for ${OPENXPKI_REALM}"
  cp -a "$OPENXPKI_CONFIG_DIR/config.d/system/realms.yaml" "/root/realms.yaml.backup.$(date +%Y%m%d%H%M%S)" 2>/dev/null || true
  cat >"$OPENXPKI_CONFIG_DIR/config.d/system/realms.yaml" <<EOF
# Generated by OpenXPKI helper production setup.
${OPENXPKI_REALM}:
    label: $(yaml_sq "$OPENXPKI_REALM_LABEL")
    baseurl: $(yaml_sq "$OPENXPKI_BASEURL")
    description: $(yaml_sq "$OPENXPKI_REALM_LABEL")
    color: "#EFD"
EOF

  rm -rf "$OPENXPKI_CONFIG_DIR/config.d/realm/${OPENXPKI_REALM}"
  mkdir -p "$OPENXPKI_CONFIG_DIR/config.d/realm"
  cp -a "$OPENXPKI_CONFIG_DIR/config.d/realm.tpl" "$OPENXPKI_CONFIG_DIR/config.d/realm/${OPENXPKI_REALM}"
  chmod -R go-rwx "$OPENXPKI_CONFIG_DIR/config.d/realm/${OPENXPKI_REALM}" 2>/dev/null || true
}

setup_cli_auth(){
  info "Configuring oxi CLI authentication key"
  install -d -m 0700 /root/.oxi
  if [[ ! -f /root/.oxi/client.key ]]; then
    openssl ecparam -name prime256v1 -genkey -noout -out /root/.oxi/client.key
    chmod 0600 /root/.oxi/client.key
  fi
  openssl ec -in /root/.oxi/client.key -pubout -out /root/.oxi/client.pub >/dev/null 2>&1
  {
    echo "auth:"
    echo "   admin:"
    echo "       role: RA Operator"
    echo "       key: |"
    sed 's/^/        /' /root/.oxi/client.pub
  } >"$OPENXPKI_CONFIG_DIR/config.d/system/cli.yaml"
  chmod 0640 "$OPENXPKI_CONFIG_DIR/config.d/system/cli.yaml"
}

write_secret_file(){
  umask 077
  cat >/root/OPENXPKI-PRODUCTION-SECRETS.txt <<EOF
OPENXPKI_REALM=${OPENXPKI_REALM}
OPENXPKI_REALM_LABEL=${OPENXPKI_REALM_LABEL}
OPENXPKI_BASEURL=${OPENXPKI_BASEURL}
OPENXPKI_DEFAULT_SECRET=${OPENXPKI_DEFAULT_SECRET}
OPENXPKI_RATOKEN_SECRET=${OPENXPKI_RATOKEN_SECRET}
OPENXPKI_SVAULT_KEY=${OPENXPKI_SVAULT_KEY}
OPENXPKI_CLI_PRIVATE_KEY=/root/.oxi/client.key
EOF
  chmod 0600 /root/OPENXPKI-PRODUCTION-SECRETS.txt
}

start_services(){
  info "Starting OpenXPKI services"
  systemctl enable --now apache2 >/dev/null 2>&1 || true
  systemctl restart openxpki-serverd >/dev/null 2>&1 || systemctl restart openxpkid >/dev/null 2>&1 || true
  sleep 5
  systemctl start openxpki-clientd >/dev/null 2>&1 || true
}

generate_issuer_material(){
  local key_dir="/etc/openxpki/local/keys/${OPENXPKI_REALM}"
  install -d -m 0700 "$key_dir"
  OPENXPKI_ISSUER_KEY="${key_dir}/issuer-ca.key"
  OPENXPKI_ISSUER_CERT="${key_dir}/issuer-ca.crt"
  info "Generating issuer CA key/certificate at ${key_dir}"
  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -out "$OPENXPKI_ISSUER_KEY"
  openssl req -x509 -new -nodes -key "$OPENXPKI_ISSUER_KEY" -sha256 -days "$OPENXPKI_CA_DAYS" -subj "$OPENXPKI_CA_SUBJECT" -out "$OPENXPKI_ISSUER_CERT"
  chmod 0600 "$OPENXPKI_ISSUER_KEY"
  chmod 0644 "$OPENXPKI_ISSUER_CERT"
}

import_issuer_token(){
  if ! command -v oxi >/dev/null 2>&1; then
    warn "oxi command not found; skipping issuer token import."
    return 0
  fi
  [[ -f "$OPENXPKI_ISSUER_CERT" && -f "$OPENXPKI_ISSUER_KEY" ]] || fail "Issuer cert/key not found."
  info "Importing issuer CA certsign token for realm ${OPENXPKI_REALM}"
  oxi token add --realm "$OPENXPKI_REALM" --type certsign --cert "$OPENXPKI_ISSUER_CERT" --key "$OPENXPKI_ISSUER_KEY" || warn "Issuer token import failed; inspect OpenXPKI service logs and rerun the oxi token command manually."
}

maybe_setup_issuer(){
  case "$OPENXPKI_CREATE_ISSUER" in
    yes|true|1) ;;
    no|false|0) warn "Skipping issuer CA creation/import by request."; return 0 ;;
    ask) ask_yes_no "Generate and import a software issuer CA token now?" "n" || return 0 ;;
    *) fail "Invalid OPENXPKI_CREATE_ISSUER=${OPENXPKI_CREATE_ISSUER}" ;;
  esac
  if [[ -z "$OPENXPKI_ISSUER_CERT" || -z "$OPENXPKI_ISSUER_KEY" ]]; then
    warn "Generating a software issuer CA. For production, consider offline/HSM-generated key material instead."
    generate_issuer_material
  fi
  import_issuer_token
}

write_completion_notes(){
  cat >/root/OPENXPKI-PRODUCTION-SETUP-RESULT.txt <<EOF
OpenXPKI production setup script completed.

Realm: ${OPENXPKI_REALM}
Base URL: ${OPENXPKI_BASEURL}
Secrets file: /root/OPENXPKI-PRODUCTION-SECRETS.txt
DB credentials file: /root/OPENXPKI-DB-CREDENTIALS.txt if openxpki-db-setup.sh was used
CLI private key: /root/.oxi/client.key
Issuer cert: ${OPENXPKI_ISSUER_CERT:-not-created-by-script}
Issuer key: ${OPENXPKI_ISSUER_KEY:-not-created-by-script}

Validate:
  systemctl status openxpki-serverd --no-pager || systemctl status openxpkid --no-pager
  systemctl status openxpki-clientd --no-pager
  oxi cli ping
  oxi token list --realm ${OPENXPKI_REALM}

If issuer import did not complete automatically, after oxi cli ping works run:
  oxi token add --realm ${OPENXPKI_REALM} --type certsign --cert <issuer.crt> --key <issuer.key>

Production reminders:
- Move generated secrets to your secret manager.
- Back up database, /etc/openxpki, /root/.oxi/client.key, and CA key material.
- Do not use script-generated issuer keys for high-assurance production PKI without review.
EOF
}

main(){
  require_root
  need openssl
  [[ -d "$OPENXPKI_CONFIG_DIR" ]] || fail "Missing ${OPENXPKI_CONFIG_DIR}; install OpenXPKI config first."
  collect_inputs
  write_system_crypto
  write_realm_config
  setup_cli_auth
  write_secret_file
  start_services
  maybe_setup_issuer
  write_completion_notes
  ok "OpenXPKI production configuration script complete. Review /root/OPENXPKI-PRODUCTION-SETUP-RESULT.txt"
}

main "$@"
